### ISSUE TITLE
Calling  .UseSignalR() on SiloBuilder Causes Grain Implementations to Not Be Found

### ISSUE THREAD

**Issue by zeus82** [OrleansContrib/SignalR.Orleans#115]
I'm really stumped with this SignalR issue... 

It looks like when I added a call to `.UseSignalR()` on my `SiloBuilder`, my cluster client throws this error whenever I try to get a grain: `System.ArgumentException: Cannot find an implementation class for grain interface: IMyGrain`. Make sure the grain assembly was correctly deployed and loaded in the silo. If I remove `.UseSignalR()`, everything works as expected. 

At first I thought it was because I was co-hosting Orleans and ASP, but I have since split them out into 2 projects and I am still seeing this error... Has anyone encountered anything like this before? 

I'm using the latest verison of Orleans and SignalR.Orleans, and my client is an ASP Core 3.1 Webapi project.

**Comment by srivathsah** [comment]
I faced the same issue and went through the code and realised we can do the equivalent of UseSignalR ourselves and actually did this 

`builder.AddSimpleMessageStreamProvider("<stream-provider-configured-in-the-cluster-service>");` instead of `builder.UseSignalR()` . The issue went away after this.  The problem was UseSignalR was adding ApplicationParts which was not right for my client application

**Comment by galvesribeiro** [comment]
That is not the exactly approach. Just like on OrleansDashboard, all you need todo is to configure the Application Parts.

Perhaps we should update the README.md with that.

Thanks!
