### ISSUE TITLE
design pattern

### ISSUE THREAD

**Issue by SalimiHabib** [OrleansContrib/SignalR.Orleans#63]
### how is it helpful in production  ### 
can we exposed orleans directly to internet ?
can we create hub in context of silo?
tank you

**Comment by claylaut** [comment]
@SalimiHabib 

1. Can we expose orleans directly to internet ?
I cant understand exactly what you're trying to achieve here but you should open this issue on the [Orleans Repo](https://github.com/dotnet/orleans/issues) directly since it's about Orlenas and not Signalr Orleans.

2. Can we create hub in context of silo?
The orignal Hub Context lives on the client side but SignalR Orleans exposes a `HubContext` which gives you the ability to send signalr messages from the grains.

**sample**
```cs
public interface IUserNotificationHub
{
    task Broadcast(UserNotification);
}

public class UserNotificationGrain : Grain<UserNotificationState>, IUserNotificationGrain
{
	private HubContext<IUserNotificationHub> _hubContext;

	public override async Task OnActivateAsync()
	{
		_hubContext = GrainFactory.GetHub<IUserNotificationHub>();
		// some code...
		await _hubContext.User(this.GetPrimaryKeyString()).SendSignalRMessage("Broadcast", State.UserNotification);
	}
}
```

Hope this helps.
